- name: Deploy nginx sites configuration
  become: yes
  template:
    src: mysite.j2
    dest: "/etc/nginx/sites-enabled/mysite"
  notify: restart nginx

- name: Remove defaults
  become: yes
  file: path="/etc/nginx/sites-enabled/default" state=absent